#!/usr/bin/env perl

# Friday before the release:
# https://confluence.tm.tmcs/confluence/display/ECOM/Current

use strict;
use warnings;

my %dates = (
	'To New Year' => '20140101',
	'To Das Ball' => '20140110',
);

my @dates_names = (
	'To New Year',
	'To Das Ball',
);

my $offset = 1;

my $seconds_today = `date -ud \$(date -u +'%Y%m%d') +%s | tr -d "\n"`;

foreach my $date_name ( @dates_names ) {
	my $seconds = `date -ud $dates{$date_name} +%s | tr -d "\n"`;
	my $days_to_date = ( ($seconds - $seconds_today) / (60*60*24) - $offset);
	print "$date_name: $days_to_date\n";
}
