#!/bin/bash
# Screencaster v3.2 2013-12-11 by Michael Ivanchenko (perlino.blogspot.com)
# http://linuxhub.ru/viewtopic.php?f=23&p=404
# Copyright (c) 2013 by Poltavchenko Dmitriy <zen@root.ua>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# Usage:
#     Start recording: ./screencaster, click on window
#     Stop recording:  q
VIDEO_DIR=~/Video
VIDEO_FILE="$(date '+%F_%H%M%S')"
VIDEO_EXT=mkv
VIDEO_PATH="$VIDEO_DIR/$VIDEO_FILE.$VIDEO_EXT"
function parseWinInfo () {
	PARAMS="$@"
	ENCODER_OPT_TPL='XWxYH -i :0.0+XOFF,YOFF'
	VAL=('XOFF' 'YOFF' 'XW' 'YH')
	for i in $PARAMS
	do
		TMP=$i
		if [[ ($NUM -ge 2) && ($(( $TMP % 2 )) != 0) ]]
		then
			TMP=$(( $TMP + 1 ))
		fi
		ENCODER_OPT_TPL=$(echo $ENCODER_OPT_TPL | sed "s/${VAL[$NUM]}/$TMP/g")
		NUM=$(( $NUM + 1 ))
	done
	echo $ENCODER_OPT_TPL
}
function getWinInfo () {
	PARAMS=$(xwininfo -frame | egrep 'Absolute|Width|Height' | awk -F: '{print $2}')
	if [[ -z $PARAMS ]]
	then
		echo 'Cannot get windows properties'
		exit 2
	fi
	echo $PARAMS
}
REGION=$(parseWinInfo $(getWinInfo))
ffmpeg -f alsa -i pulse -f x11grab -framerate 24 -show_region 1 -threads 4 \
	-q 1 -bt 8000000 -b 8500000 -y -video_size $REGION $VIDEO_PATH
